### ISSUE TITLE
P value adjustment when using exclude option

### ISSUE THREAD

**Issue by jwbenning** [rvlenth/emmeans#107]
I think this is a very minor bug, but when I use the `exclude` argument in `emmeans()`, the size of the test family isn't being updated. E.g., if the factor has 6 levels, but in `emmeans()` I specify to exclude three of them in pairwise contrasts, the tukey adjustment for the p values is based on a family of 6 estimates. Example using iris

````
iris.4sp <- iris
# need to add a 4th species to illustrate bug
iris.4sp$Species <- as.character(iris.4sp$Species)
iris.4sp$Species[iris.4sp$Sepal.Length < 5] <- 'newSp'
iris.4sp$Species <- as.factor(iris.4sp$Species) # change back to factor

sepals.lm <- lm(Sepal.Length ~ Species, data = iris.4sp)
emmeans(sepals.lm, pairwise ~ Species)
emmeans(sepals.lm, pairwise ~ Species, exclude = c("setosa"))
emmeans(sepals.lm, pairwise ~ Species, exclude = c("setosa"), adjust = "tukey")
emmeans(sepals.lm, pairwise ~ Species, exclude = c("setosa"), adjust = "bonferroni")
````

It doesn't get the family size right when I explicitly specify a tukey adjustment, either, but does with other adjustments (bonferroni, etc). I think it's just a bug with tukey. Unless I'm missing something and the family size shouldn't change!

Thanks so much,

John

**Comment by rvlenth** [comment]
Well this is embarrassing. Now that you call this to my attention, I *know* that I overlooked adjusting the family size under those circumstances, because I know I didn't look beyond the contrast functions when I added the `exclude` and `include` options. Thanks for reporting it. I have fixed it:
```r
> warp.lm <- lm(breaks ~ wool * tension, data = warpbreaks)

> summary(pairs(ref_grid(warp.lm)))
 contrast  estimate   SE df t.ratio p.value
 A,L - B,L   16.333 5.16 48  3.167  0.0302 
 A,L - A,M   20.556 5.16 48  3.986  0.0030 
 A,L - B,M   15.778 5.16 48  3.059  0.0398 
 A,L - A,H   20.000 5.16 48  3.878  0.0041 
 A,L - B,H   25.778 5.16 48  4.998  0.0001 
 B,L - A,M    4.222 5.16 48  0.819  0.9627 
 B,L - B,M   -0.556 5.16 48 -0.108  1.0000 
 B,L - A,H    3.667 5.16 48  0.711  0.9797 
 B,L - B,H    9.444 5.16 48  1.831  0.4561 
 A,M - B,M   -4.778 5.16 48 -0.926  0.9377 
 A,M - A,H   -0.556 5.16 48 -0.108  1.0000 
 A,M - B,H    5.222 5.16 48  1.013  0.9115 
 B,M - A,H    4.222 5.16 48  0.819  0.9627 
 B,M - B,H   10.000 5.16 48  1.939  0.3919 
 A,H - B,H    5.778 5.16 48  1.120  0.8706 

P value adjustment: tukey method for comparing a family of 6 estimates 

> summary(pairs(ref_grid(warp.lm), exclude = 3:4))
 contrast  estimate   SE df t.ratio p.value
 A,L - B,L    16.33 5.16 48 3.167   0.0138 
 A,L - A,H    20.00 5.16 48 3.878   0.0018 
 A,L - B,H    25.78 5.16 48 4.998   <.0001 
 B,L - A,H     3.67 5.16 48 0.711   0.8923 
 B,L - B,H     9.44 5.16 48 1.831   0.2716 
 A,H - B,H     5.78 5.16 48 1.120   0.6789 

P value adjustment: tukey method for comparing a family of 4 estimates
```
I'll close this but you may still comment if you like.

**Comment by jwbenning** [comment]
Thanks so much! Maybe fastest bug fix...ever???

**Comment by jwbenning** [comment]
I updated from GitHub, but this code:
`emmeans(nodes.lm, pairwise ~ inoc|seed, exclude = c("CO", "KV", "BI"), data = microbeLA)`

still gets the family size wrong.  It gives me the right contrasts, excluding the ones I specify, but the family size is still 6 (instead of 3).

**Comment by jwbenning** [comment]
for reproducibility, the `iris` example I gave also still gives the wrong family size, as well

**Comment by rvlenth** [comment]
Traveling. It’ll be awhile before I can look at this again.

Sent from my iPhone

On May 14, 2019, at 10:43 AM, John Benning <notifications@github.com<mailto:notifications@github.com>> wrote:


for reproducibility, the iris example I gave also still gives the wrong family size, as well

**Comment by rvlenth** [comment]
This all looks correct to me. I think perhaps you still had the old version loaded in memory, or the build failed?

```r
> library(emmeans)
> iris.4sp <- iris
> # need to add a 4th species to illustrate bug
> iris.4sp$Species <- as.character(iris.4sp$Species)
> iris.4sp$Species[iris.4sp$Sepal.Length < 5] <- 'newSp'
> iris.4sp$Species <- as.factor(iris.4sp$Species) # change back to factor
> 
> sepals.lm <- lm(Sepal.Length ~ Species, data = iris.4sp)
> emmeans(sepals.lm, pairwise ~ Species)
$`emmeans`
 Species    emmean     SE  df lower.CL upper.CL
 newSp        4.69 0.0987 146     4.50     4.89
 setosa       5.23 0.0845 146     5.06     5.40
 versicolor   5.96 0.0661 146     5.83     6.09
 virginica    6.62 0.0661 146     6.49     6.75

Confidence level used: 0.95 

$contrasts
 contrast               estimate     SE  df t.ratio p.value
 newSp - setosa           -0.539 0.1299 146  -4.149 0.0003 
 newSp - versicolor       -1.266 0.1188 146 -10.658 <.0001 
 newSp - virginica        -1.932 0.1188 146 -16.259 <.0001 
 setosa - versicolor      -0.727 0.1073 146  -6.776 <.0001 
 setosa - virginica       -1.392 0.1073 146 -12.975 <.0001 
 versicolor - virginica   -0.665 0.0935 146  -7.114 <.0001 

P value adjustment: tukey method for comparing a family of 4 estimates 

> emmeans(sepals.lm, pairwise ~ Species, exclude = c("setosa"))
$`emmeans`
 Species    emmean     SE  df lower.CL upper.CL
 newSp        4.69 0.0987 146     4.50     4.89
 setosa       5.23 0.0845 146     5.06     5.40
 versicolor   5.96 0.0661 146     5.83     6.09
 virginica    6.62 0.0661 146     6.49     6.75

Confidence level used: 0.95 

$contrasts
 contrast               estimate     SE  df t.ratio p.value
 newSp - versicolor       -1.266 0.1188 146 -10.658 <.0001 
 newSp - virginica        -1.932 0.1188 146 -16.259 <.0001 
 versicolor - virginica   -0.665 0.0935 146  -7.114 <.0001 

P value adjustment: tukey method for comparing a family of 3 estimates 

> emmeans(sepals.lm, pairwise ~ Species, exclude = c("setosa"), adjust = "tukey")
$`emmeans`
 Species    emmean     SE  df lower.CL upper.CL
 newSp        4.69 0.0987 146     4.50     4.89
 setosa       5.23 0.0845 146     5.06     5.40
 versicolor   5.96 0.0661 146     5.83     6.09
 virginica    6.62 0.0661 146     6.49     6.75

Confidence level used: 0.95 

$contrasts
 contrast               estimate     SE  df t.ratio p.value
 newSp - versicolor       -1.266 0.1188 146 -10.658 <.0001 
 newSp - virginica        -1.932 0.1188 146 -16.259 <.0001 
 versicolor - virginica   -0.665 0.0935 146  -7.114 <.0001 

P value adjustment: tukey method for comparing a family of 3 estimates 

> emmeans(sepals.lm, pairwise ~ Species, exclude = c("setosa"), adjust = "bonferroni")
$`emmeans`
 Species    emmean     SE  df lower.CL upper.CL
 newSp        4.69 0.0987 146     4.50     4.89
 setosa       5.23 0.0845 146     5.06     5.40
 versicolor   5.96 0.0661 146     5.83     6.09
 virginica    6.62 0.0661 146     6.49     6.75

Confidence level used: 0.95 

$contrasts
 contrast               estimate     SE  df t.ratio p.value
 newSp - versicolor       -1.266 0.1188 146 -10.658 <.0001 
 newSp - virginica        -1.932 0.1188 146 -16.259 <.0001 
 versicolor - virginica   -0.665 0.0935 146  -7.114 <.0001 

P value adjustment: bonferroni method for 3 tests
```

**Comment by jwbenning** [comment]
You're right! It's working now; the old version must have been loaded.

Thanks again!
